// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from UE_msgs/SetElevatorFloorDestination.srv - do not modify

#include "Srvs/ROS2SetElevatorFloorDestinationSrv.h"

const rosidl_service_type_support_t* UROS2SetElevatorFloorDestinationSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(ue_msgs, srv, SetElevatorFloorDestination);
}

void UROS2SetElevatorFloorDestinationSrv::Init()
{
    ue_msgs__srv__SetElevatorFloorDestination_Request__init(&SetElevatorFloorDestination_req);
    ue_msgs__srv__SetElevatorFloorDestination_Response__init(&SetElevatorFloorDestination_res);
}

void UROS2SetElevatorFloorDestinationSrv::Fini()
{
    ue_msgs__srv__SetElevatorFloorDestination_Request__fini(&SetElevatorFloorDestination_req);
    ue_msgs__srv__SetElevatorFloorDestination_Response__fini(&SetElevatorFloorDestination_res);
}

void UROS2SetElevatorFloorDestinationSrv::SetRequest(const FROSSetElevatorFloorDestination_Request& Request)
{
    Request.SetROS2(SetElevatorFloorDestination_req);
}

void UROS2SetElevatorFloorDestinationSrv::GetRequest(FROSSetElevatorFloorDestination_Request& Request) const
{
    Request.SetFromROS2(SetElevatorFloorDestination_req);
}

void UROS2SetElevatorFloorDestinationSrv::SetResponse(const FROSSetElevatorFloorDestination_Response& Response)
{
    Response.SetROS2(SetElevatorFloorDestination_res);
}

void UROS2SetElevatorFloorDestinationSrv::GetResponse(FROSSetElevatorFloorDestination_Response& Response) const
{
    Response.SetFromROS2(SetElevatorFloorDestination_res);
}

void* UROS2SetElevatorFloorDestinationSrv::GetRequest()
{
    return &SetElevatorFloorDestination_req;
}

void* UROS2SetElevatorFloorDestinationSrv::GetResponse()
{
    return &SetElevatorFloorDestination_res;
}

FString UROS2SetElevatorFloorDestinationSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2SetElevatorFloorDestinationSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}