// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from UE_msgs/GetElevatorStatus.srv - do not modify

#include "Srvs/ROS2GetElevatorStatusSrv.h"

const rosidl_service_type_support_t* UROS2GetElevatorStatusSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(ue_msgs, srv, GetElevatorStatus);
}

void UROS2GetElevatorStatusSrv::Init()
{
    ue_msgs__srv__GetElevatorStatus_Request__init(&GetElevatorStatus_req);
    ue_msgs__srv__GetElevatorStatus_Response__init(&GetElevatorStatus_res);
}

void UROS2GetElevatorStatusSrv::Fini()
{
    ue_msgs__srv__GetElevatorStatus_Request__fini(&GetElevatorStatus_req);
    ue_msgs__srv__GetElevatorStatus_Response__fini(&GetElevatorStatus_res);
}

void UROS2GetElevatorStatusSrv::SetRequest(const FROSGetElevatorStatus_Request& Request)
{
    Request.SetROS2(GetElevatorStatus_req);
}

void UROS2GetElevatorStatusSrv::GetRequest(FROSGetElevatorStatus_Request& Request) const
{
    Request.SetFromROS2(GetElevatorStatus_req);
}

void UROS2GetElevatorStatusSrv::SetResponse(const FROSGetElevatorStatus_Response& Response)
{
    Response.SetROS2(GetElevatorStatus_res);
}

void UROS2GetElevatorStatusSrv::GetResponse(FROSGetElevatorStatus_Response& Response) const
{
    Response.SetFromROS2(GetElevatorStatus_res);
}

void* UROS2GetElevatorStatusSrv::GetRequest()
{
    return &GetElevatorStatus_req;
}

void* UROS2GetElevatorStatusSrv::GetResponse()
{
    return &GetElevatorStatus_res;
}

FString UROS2GetElevatorStatusSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2GetElevatorStatusSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}