// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from UE_msgs/SetElevatorFloorDestination.srv - do not modify

#pragma once

#include <CoreMinimal.h>

#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"
#include "ue_msgs/srv/set_elevator_floor_destination.h"

#include "ROS2SetElevatorFloorDestinationSrv.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct RCLUE_API FROSSetElevatorFloorDestination_Request
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int floor_destination;

	

	void SetFromROS2(const ue_msgs__srv__SetElevatorFloorDestination_Request& in_ros_data)
	{
    	floor_destination = in_ros_data.floor_destination;

		
	}

	void SetROS2(ue_msgs__srv__SetElevatorFloorDestination_Request& out_ros_data) const
	{
    	out_ros_data.floor_destination = floor_destination;

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSSetElevatorFloorDestination_Response
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool success;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString remarks;

	

	void SetFromROS2(const ue_msgs__srv__SetElevatorFloorDestination_Response& in_ros_data)
	{
    	success = in_ros_data.success;

		remarks.AppendChars(in_ros_data.remarks.data, in_ros_data.remarks.size);

		
	}

	void SetROS2(ue_msgs__srv__SetElevatorFloorDestination_Response& out_ros_data) const
	{
    	out_ros_data.success = success;

		{
			FTCHARToUTF8 strUtf8( *remarks );
			int32 strLength = strUtf8.Length();
			if (out_ros_data.remarks.data != nullptr)
		{
			free(out_ros_data.remarks.data);
		}
		out_ros_data.remarks.data = (decltype(out_ros_data.remarks.data))malloc((strLength+1)*sizeof(decltype(*out_ros_data.remarks.data)));
		memcpy(out_ros_data.remarks.data, TCHAR_TO_UTF8(*remarks), (strLength+1)*sizeof(char));
			out_ros_data.remarks.size = strLength;
			out_ros_data.remarks.capacity = strLength + 1;
		}

		
	}
};

UCLASS()
class RCLUE_API UROS2SetElevatorFloorDestinationSrv : public UROS2GenericSrv
{
	GENERATED_BODY()

public:
  	UFUNCTION(BlueprintCallable)
	virtual void Init() override;

  	UFUNCTION(BlueprintCallable)
	virtual void Fini() override;

	virtual const rosidl_service_type_support_t* GetTypeSupport() const override;
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void SetRequest(const FROSSetElevatorFloorDestination_Request& Request);
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void GetRequest(FROSSetElevatorFloorDestination_Request& Request) const;
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void SetResponse(const FROSSetElevatorFloorDestination_Response& Response);
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void GetResponse(FROSSetElevatorFloorDestination_Response& Response) const;
	
	virtual void* GetRequest() override;
	virtual void* GetResponse() override;

private:
	virtual FString SrvRequestToString() const override;
	virtual FString SrvResponseToString() const override;

	ue_msgs__srv__SetElevatorFloorDestination_Request SetElevatorFloorDestination_req;
	ue_msgs__srv__SetElevatorFloorDestination_Response SetElevatorFloorDestination_res;
};