// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from UE_msgs/GetElevatorStatus.srv - do not modify

#pragma once

#include <CoreMinimal.h>

#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"
#include "ue_msgs/srv/get_elevator_status.h"

#include "ROS2GetElevatorStatusSrv.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct RCLUE_API FROSGetElevatorStatus_Request
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool dummy;

	

	void SetFromROS2(const ue_msgs__srv__GetElevatorStatus_Request& in_ros_data)
	{
    	dummy = in_ros_data.dummy;

		
	}

	void SetROS2(ue_msgs__srv__GetElevatorStatus_Request& out_ros_data) const
	{
    	out_ros_data.dummy = dummy;

		
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSGetElevatorStatus_Response
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool success;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool door_open;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int current_floor;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int nb_reservations;

	

	void SetFromROS2(const ue_msgs__srv__GetElevatorStatus_Response& in_ros_data)
	{
    	success = in_ros_data.success;

		door_open = in_ros_data.door_open;

		current_floor = in_ros_data.current_floor;

		nb_reservations = in_ros_data.nb_reservations;

		
	}

	void SetROS2(ue_msgs__srv__GetElevatorStatus_Response& out_ros_data) const
	{
    	out_ros_data.success = success;

		out_ros_data.door_open = door_open;

		out_ros_data.current_floor = current_floor;

		out_ros_data.nb_reservations = nb_reservations;

		
	}
};

UCLASS()
class RCLUE_API UROS2GetElevatorStatusSrv : public UROS2GenericSrv
{
	GENERATED_BODY()

public:
  	UFUNCTION(BlueprintCallable)
	virtual void Init() override;

  	UFUNCTION(BlueprintCallable)
	virtual void Fini() override;

	virtual const rosidl_service_type_support_t* GetTypeSupport() const override;
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void SetRequest(const FROSGetElevatorStatus_Request& Request);
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void GetRequest(FROSGetElevatorStatus_Request& Request) const;
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void SetResponse(const FROSGetElevatorStatus_Response& Response);
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void GetResponse(FROSGetElevatorStatus_Response& Response) const;
	
	virtual void* GetRequest() override;
	virtual void* GetResponse() override;

private:
	virtual FString SrvRequestToString() const override;
	virtual FString SrvResponseToString() const override;

	ue_msgs__srv__GetElevatorStatus_Request GetElevatorStatus_req;
	ue_msgs__srv__GetElevatorStatus_Response GetElevatorStatus_res;
};